$SERVER_B_IP = "your-server-b-ip"
$SSH_USER = "root"
$SSH_EXE = "ssh"
$SCP_EXE = "scp"
foreach ($p in @(
    "C:\Program Files\Git\usr\bin\ssh.exe",
    "C:\Program Files (x86)\Git\usr\bin\ssh.exe",
    "C:\Program Files\Git\usr\bin\ssh.exe",
    "C:\Users\Administrator\AppData\Local\Programs\Git\usr\bin\ssh.exe"
)) {
    if (Test-Path $p) {
        $SSH_EXE = $p
        $SCP_EXE = $p.Replace('\usr\bin\ssh.exe', '\usr\bin\scp.exe')
        break
    }
}
Write-Host "Generating and uploading docker-compose.yml..." -ForegroundColor Cyan
$tmpYml = Join-Path $env:TEMP "autocode-storage.yml"
$dockerCompose = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('dmVyc2lvbjogJzMuOCcKc2VydmljZXM6CiAgcmVkaXM6CiAgICBpbWFnZTogcmVkaXM6Ny1hbHBpbmUKICAgIHJlc3RhcnQ6IGFsd2F5cwogICAgbmV0d29ya19tb2RlOiBob3N0CiAgICBjb21tYW5kOiByZWRpcy1zZXJ2ZXIgLS1iaW5kIDEyNy4wLjAuMSAtLXBvcnQgNjM3OSAtLW1heG1lbW9yeSA0Z2IgLS1tYXhtZW1vcnktcG9saWN5IGFsbGtleXMtbHJ1CiAgICB2b2x1bWVzOgogICAgICAtIC9kYXRhL2F1dG9jb2RlLXN0b3JhZ2UvcmVkaXM6L2RhdGEKICAgIGhlYWx0aGNoZWNrOgogICAgICB0ZXN0OiBbIkNNRCIsICJyZWRpcy1jbGkiLCAicGluZyJdCiAgICAgIGludGVydmFsOiAxMHMKICAgICAgdGltZW91dDogNXMKICAgICAgcmV0cmllczogMwogIGVsYXN0aWNzZWFyY2g6CiAgICBpbWFnZTogZWxhc3RpY3NlYXJjaDo4LjEzLjAKICAgIHJlc3RhcnQ6IGFsd2F5cwogICAgbmV0d29ya19tb2RlOiBob3N0CiAgICBlbnZpcm9ubWVudDoKICAgICAgLSBkaXNjb3ZlcnkudHlwZT1zaW5nbGUtbm9kZQogICAgICAtIEVTX0pBVkFfT1BUUz0tWG1zNGcgLVhteDRnCiAgICAgIC0geHBhY2suc2VjdXJpdHkuZW5hYmxlZD1mYWxzZQogICAgICAtIHhwYWNrLnNlY3VyaXR5LmVucm9sbG1lbnQuZW5hYmxlZD1mYWxzZQogICAgICAtIHhwYWNrLnNlY3VyaXR5Lmh0dHAuc3NsLmVuYWJsZWQ9ZmFsc2UKICAgICAgLSB4cGFjay5zZWN1cml0eS50cmFuc3BvcnQuc3NsLmVuYWJsZWQ9ZmFsc2UKICAgICAgLSBuZXR3b3JrLmhvc3Q9MTI3LjAuMC4xCiAgICAgIC0gaHR0cC5wb3J0PTkyMDAKICAgIHVsaW1pdHM6CiAgICAgIG1lbWxvY2s6IHsgc29mdDogLTEsIGhhcmQ6IC0xIH0KICAgICAgbm9maWxlOiB7IHNvZnQ6IDY1NTM1LCBoYXJkOiA2NTUzNSB9CiAgICB2b2x1bWVzOgogICAgICAtIC9kYXRhL2F1dG9jb2RlLXN0b3JhZ2UvZXM6L3Vzci9zaGFyZS9lbGFzdGljc2VhcmNoL2RhdGEKICAgIGhlYWx0aGNoZWNrOgogICAgICB0ZXN0OiBbIkNNRC1TSEVMTCIsICJjdXJsIC1zZiBodHRwOi8vMTI3LjAuMC4xOjkyMDAvX2NsdXN0ZXIvaGVhbHRoIHx8IGV4aXQgMSJdCiAgICAgIGludGVydmFsOiAzMHMKICAgICAgdGltZW91dDogMTBzCiAgICAgIHJldHJpZXM6IDUKICBtaWx2dXM6CiAgICBpbWFnZTogbWlsdnVzZGIvbWlsdnVzOnYyLjQuMAogICAgcmVzdGFydDogYWx3YXlzCiAgICBuZXR3b3JrX21vZGU6IGhvc3QKICAgIGVudmlyb25tZW50OgogICAgICAtIEVUQ0RfVVNFX0VNQkVEPXRydWUKICAgICAgLSBFVENEX0RBVEFfRElSPS92YXIvbGliL21pbHZ1cy9ldGNkCiAgICAgIC0gTUVUUklDU19QT1JUPTkwOTEKICAgICAgLSBjb21tb24uc2VjdXJpdHkuYXV0aG9yaXphdGlvbkVuYWJsZWQ9ZmFsc2UKICAgICAgLSBjb21tb24uc2VjdXJpdHkudGxzTW9kZT0wCiAgICAgIC0gbmV0d29yay5iaW5kSW50ZXJmYWNlPTEyNy4wLjAuMQogICAgICAtIG15U3FsLnVybD1zcWxpdGU6Ly8vdmFyL2xpYi9taWx2dXMvbWV0YS5zcWxpdGUKICAgIHVsaW1pdHM6CiAgICAgIG5vZmlsZTogeyBzb2Z0OiA2NTUzNSwgaGFyZDogNjU1MzUgfQogICAgdm9sdW1lczoKICAgICAgLSAvZGF0YS9hdXRvY29kZS1zdG9yYWdlL21pbHZ1czovdmFyL2xpYi9taWx2dXMKICAgIGhlYWx0aGNoZWNrOgogICAgICB0ZXN0OiBbIkNNRC1TSEVMTCIsICJjdXJsIC1zZiBodHRwOi8vMTI3LjAuMC4xOjkwOTEvaGVhbHRoeiB8fCBleGl0IDEiXQogICAgICBpbnRlcnZhbDogMzBzCiAgICAgIHRpbWVvdXQ6IDEwcwogICAgICByZXRyaWVzOiA1'))
[System.IO.File]::WriteAllText($tmpYml, $dockerCompose, (New-Object System.Text.UTF8Encoding($false)))
$target = "${SSH_USER}@${SERVER_B_IP}:/opt/autocode/storage/docker-compose.yml"
& $SCP_EXE -o StrictHostKeyChecking=no $tmpYml $target
if ($LASTEXITCODE -ne 0) { Write-Host "Upload failed" -ForegroundColor Red; exit 1 }

Write-Host "Deploying storage components..." -ForegroundColor Cyan
$hostArg = "${SSH_USER}@${SERVER_B_IP}"
$decodedSetup = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('c2V0IC1lCm1rZGlyIC1wIC9kYXRhL2F1dG9jb2RlLXN0b3JhZ2UvcmVkaXMgL2RhdGEvYXV0b2NvZGUtc3RvcmFnZS9lcyAvZGF0YS9hdXRvY29kZS1zdG9yYWdlL21pbHZ1cwpjaG1vZCA3NzcgL2RhdGEvYXV0b2NvZGUtc3RvcmFnZSAtUgppZiAhIGNvbW1hbmQgLXYgZG9ja2VyID4gL2Rldi9udWxsIDI+JjE7IHRoZW4KICBlY2hvICJJbnN0YWxsaW5nIERvY2tlci4uLiIKICBjdXJsIC1mc1NMIGh0dHBzOi8vZ2V0LmRvY2tlci5jb20gLW8gZ2V0LWRvY2tlci5zaAogIHNoIGdldC1kb2NrZXIuc2ggLS1taXJyb3IgQWxpeXVuCiAgc3lzdGVtY3RsIGVuYWJsZSAtLW5vdyBkb2NrZXIKZmkKaWYgISBjb21tYW5kIC12IGRvY2tlci1jb21wb3NlID4gL2Rldi9udWxsIDI+JjE7IHRoZW4KICBlY2hvICJJbnN0YWxsaW5nIERvY2tlciBDb21wb3NlLi4uIgogIGN1cmwgLVNMIGh0dHBzOi8vZ2l0aHViLmNvbS9kb2NrZXIvY29tcG9zZS9yZWxlYXNlcy9kb3dubG9hZC92Mi4yNy4wL2RvY2tlci1jb21wb3NlLWxpbnV4LXg4Nl82NCAtbyAvdXNyL2xvY2FsL2Jpbi9kb2NrZXItY29tcG9zZQogIGNobW9kICt4IC91c3IvbG9jYWwvYmluL2RvY2tlci1jb21wb3NlCmZpCmNkIC9vcHQvYXV0b2NvZGUvc3RvcmFnZQpkb2NrZXItY29tcG9zZSBkb3duIC0tcmVtb3ZlLW9ycGhhbnMKZG9ja2VyLWNvbXBvc2UgdXAgLWQKZWNobyAiV2FpdGluZyBmb3Igc2VydmljZXMgKDMwcykuLi4iCnNsZWVwIDMwCmVjaG8gIj09PT09IFJlc3VsdHMgPT09PT0iCmVjaG8gLW4gIlJlZGlzOiAiCmRvY2tlciBleGVjIHN0b3JhZ2UtcmVkaXMtMSByZWRpcy1jbGkgcGluZyB8IGdyZXAgLXEgUE9ORyAmJiBlY2hvICJPSyIgfHwgZWNobyAiRkFJTEVEIgplY2hvIC1uICJFUzogIgpjdXJsIC1zZiBodHRwOi8vMTI3LjAuMC4xOjkyMDAvX2NsdXN0ZXIvaGVhbHRoIHwgZ3JlcCAtcSBncmVlbiAmJiBlY2hvICJPSyIgfHwgZWNobyAiRkFJTEVEIgplY2hvIC1uICJNaWx2dXM6ICIKY3VybCAtc2YgaHR0cDovLzEyNy4wLjAuMTo5MDkxL2hlYWx0aHogfCBncmVwIC1xIE9LICYmIGVjaG8gIk9LIiB8fCBlY2hvICJGQUlMRUQiCmVjaG8gIj09PT09IERvbmUgPT09PT0i'))
& $SSH_EXE -o StrictHostKeyChecking=no $hostArg $decodedSetup

Remove-Item $tmpYml -Force -ErrorAction SilentlyContinue
if ($LASTEXITCODE -eq 0) { Write-Host "Done" -ForegroundColor Green } else { Write-Host "Failed" -ForegroundColor Red }
