-- Workflow Engine V2 tables.
-- Safe to run repeatedly: all tables use CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS workflow_artifact (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid            VARCHAR(64)  NOT NULL UNIQUE COMMENT 'Artifact UUID',
    user_id         BIGINT       NOT NULL COMMENT 'Owner user ID',
    conversation_id BIGINT       COMMENT 'Source conversation ID',
    workflow_id     BIGINT       COMMENT 'Workflow ID',
    execution_id    BIGINT       COMMENT 'Workflow execution ID',
    step_id         VARCHAR(64)  COMMENT 'Source step ID',
    source_type     VARCHAR(50)  NOT NULL DEFAULT 'upload' COMMENT 'upload/workflow_output/asr/vision/document_parse',
    file_name       VARCHAR(500) COMMENT 'Original file name',
    file_type       VARCHAR(50)  NOT NULL DEFAULT 'other' COMMENT 'image/document/spreadsheet/audio/video/text/other',
    mime_type       VARCHAR(100) COMMENT 'MIME type',
    file_size       BIGINT       NOT NULL DEFAULT 0 COMMENT 'File size in bytes',
    oss_url         VARCHAR(1000) COMMENT 'OSS URL',
    object_key      VARCHAR(1000) COMMENT 'OSS object key',
    content_text    MEDIUMTEXT   COMMENT 'Small text result or summary',
    metadata_json   TEXT         COMMENT 'Structured metadata JSON',
    status          VARCHAR(20)  NOT NULL DEFAULT 'ready' COMMENT 'pending/ready/failed',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0,
    INDEX idx_wa_user_id (user_id),
    INDEX idx_wa_workflow_id (workflow_id),
    INDEX idx_wa_execution_id (execution_id),
    INDEX idx_wa_step_id (step_id),
    INDEX idx_wa_file_type (file_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Workflow artifact table';

CREATE TABLE IF NOT EXISTS workflow_artifact_upload_session (
    id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    upload_id          VARCHAR(64)  NOT NULL UNIQUE COMMENT 'Platform upload session UUID',
    user_id            BIGINT       NOT NULL COMMENT 'Owner user ID',
    file_name          VARCHAR(500) NOT NULL COMMENT 'Original file name',
    total_size         BIGINT       NOT NULL COMMENT 'Total file size in bytes',
    chunk_size         BIGINT       NOT NULL COMMENT 'Chunk size in bytes',
    total_parts        INT          NOT NULL COMMENT 'Total chunk count',
    uploaded_parts     TEXT         COMMENT 'Uploaded part numbers as JSON array',
    content_type       VARCHAR(100) COMMENT 'MIME type',
    workflow_id        BIGINT       COMMENT 'Workflow ID',
    execution_id       BIGINT       COMMENT 'Workflow execution ID',
    step_id            VARCHAR(64)  COMMENT 'Source step ID',
    source_type        VARCHAR(50)  NOT NULL DEFAULT 'upload',
    conversation_id    BIGINT       COMMENT 'Source conversation ID',
    sync_to_work_file  TINYINT      NOT NULL DEFAULT 0,
    metadata_json      TEXT         COMMENT 'Artifact metadata JSON',
    storage_mode       VARCHAR(32)  NOT NULL DEFAULT 'oss_temp_merge' COMMENT 'oss_temp_merge/native_multipart',
    temp_dir           VARCHAR(1000) COMMENT 'Server temp directory',
    object_key         VARCHAR(1000) COMMENT 'Reserved OSS object key',
    native_upload_id   VARCHAR(255) COMMENT 'Reserved cloud native multipart upload ID',
    status             VARCHAR(20)  NOT NULL DEFAULT 'pending' COMMENT 'pending/uploading/completed/failed/aborted',
    error_msg          TEXT         COMMENT 'Last error message',
    created_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    expires_at         DATETIME     COMMENT 'Session expiration time',
    deleted            TINYINT      NOT NULL DEFAULT 0,
    INDEX idx_waus_user_id (user_id),
    INDEX idx_waus_upload_id (upload_id),
    INDEX idx_waus_status (status),
    INDEX idx_waus_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Workflow artifact upload session table';

CREATE TABLE IF NOT EXISTS workflow_execution_step (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    execution_id    BIGINT       NOT NULL COMMENT 'Execution ID',
    workflow_id     BIGINT       NOT NULL COMMENT 'Workflow ID',
    step_id         VARCHAR(64)  NOT NULL COMMENT 'DSL step ID',
    step_name       VARCHAR(200) COMMENT 'Step name or description',
    tool_name       VARCHAR(128) COMMENT 'Tool name',
    status          VARCHAR(20)  NOT NULL DEFAULT 'running' COMMENT 'running/completed/skipped/failed/cancelled',
    input_json      TEXT         COMMENT 'Step input JSON',
    output_json     MEDIUMTEXT   COMMENT 'Step output JSON',
    error_msg       TEXT         COMMENT 'Error message',
    started_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at     DATETIME     COMMENT 'Finished time',
    duration_ms     INT          DEFAULT 0 COMMENT 'Duration in milliseconds',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0,
    INDEX idx_wes_execution_id (execution_id),
    INDEX idx_wes_workflow_id (workflow_id),
    INDEX idx_wes_step_id (step_id),
    INDEX idx_wes_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Workflow execution step table';

CREATE TABLE IF NOT EXISTS workflow_execution_event (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    execution_id    BIGINT       NOT NULL COMMENT 'Execution ID',
    step_id         VARCHAR(64)  COMMENT 'Step ID',
    event_type      VARCHAR(50)  NOT NULL COMMENT 'Event type',
    message         VARCHAR(1000) COMMENT 'Event message',
    payload_json    TEXT         COMMENT 'Event payload JSON',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0,
    INDEX idx_wee_execution_id (execution_id),
    INDEX idx_wee_step_id (step_id),
    INDEX idx_wee_event_type (event_type),
    INDEX idx_wee_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Workflow execution event table';

CREATE TABLE IF NOT EXISTS workflow_execution_checkpoint (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    execution_id    BIGINT       NOT NULL COMMENT 'Execution ID',
    workflow_id     BIGINT       NOT NULL COMMENT 'Workflow ID',
    step_id         VARCHAR(64)  NOT NULL COMMENT 'DSL step ID',
    step_record_id  BIGINT       COMMENT 'workflow_execution_step.id',
    status          VARCHAR(20)  NOT NULL DEFAULT 'completed' COMMENT 'completed/skipped/failed/cancelled',
    input_json      TEXT         COMMENT 'Checkpoint input JSON',
    output_json     MEDIUMTEXT   COMMENT 'Checkpoint output JSON',
    error_msg       TEXT         COMMENT 'Error message',
    duration_ms     INT          DEFAULT 0 COMMENT 'Duration in milliseconds',
    completed_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Checkpoint completion time',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted         TINYINT      NOT NULL DEFAULT 0,
    UNIQUE KEY uk_wec_execution_step (execution_id, step_id, deleted),
    INDEX idx_wec_execution_id (execution_id),
    INDEX idx_wec_workflow_id (workflow_id),
    INDEX idx_wec_step_id (step_id),
    INDEX idx_wec_status (status),
    INDEX idx_wec_completed_at (completed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Workflow execution checkpoint table';
