-- AutoCode task persistence table.
-- Target database: MuHuoAi.

CREATE TABLE IF NOT EXISTS `autocode_tasks` (
    `id` VARCHAR(64) NOT NULL COMMENT 'Task id',
    `title` VARCHAR(200) NOT NULL COMMENT 'Task title',
    `description` TEXT NOT NULL COMMENT 'User requirement',
    `project_type` VARCHAR(50) NOT NULL DEFAULT 'unknown' COMMENT 'Project type',
    `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'Task status',
    `progress` INT NOT NULL DEFAULT 0 COMMENT 'Progress 0-100',
    `current_step` VARCHAR(500) DEFAULT '' COMMENT 'Current step',
    `workspace_id` VARCHAR(64) DEFAULT NULL COMMENT 'Workspace id',
    `user_id` VARCHAR(64) DEFAULT NULL COMMENT 'Owner user id',
    `harness_trace_id` BIGINT DEFAULT NULL COMMENT 'Linked harness trace id',
    `model` VARCHAR(100) DEFAULT NULL COMMENT 'Selected model',
    `tool_policy` VARCHAR(32) NOT NULL DEFAULT 'full_access' COMMENT 'Tool permission policy',
    `autonomy_mode` VARCHAR(20) NOT NULL DEFAULT 'strong' COMMENT 'Agent autonomy mode',
    `agents` JSON DEFAULT NULL COMMENT 'Enabled agent types',
    `preview_url` VARCHAR(500) DEFAULT NULL COMMENT 'Preview URL',
    `logs` JSON DEFAULT NULL COMMENT 'Execution and chat logs',
    `commit_history` JSON DEFAULT NULL COMMENT 'Git commit history',
    `plan` JSON DEFAULT NULL COMMENT 'AutoCode task plan',
    `review` JSON DEFAULT NULL COMMENT 'Final code review result',
    `phase_reviews` JSON DEFAULT NULL COMMENT 'Per-phase code review results',
    `prototype` JSON DEFAULT NULL COMMENT 'UI prototype data',
    `plan_confirmed` TINYINT(1) DEFAULT NULL COMMENT 'Whether the plan was confirmed',
    `prototype_confirmed` TINYINT(1) DEFAULT NULL COMMENT 'Whether the prototype was confirmed',
    `review_confirmed` TINYINT(1) DEFAULT NULL COMMENT 'Whether the final review was confirmed',
    `current_subtask_id` VARCHAR(64) DEFAULT NULL COMMENT 'Current subtask id',
    `project_recon` JSON DEFAULT NULL COMMENT 'Project reconnaissance result',
    `complexity` VARCHAR(20) DEFAULT NULL COMMENT 'Task complexity',
    `recommended_flow` VARCHAR(80) DEFAULT NULL COMMENT 'Recommended flow',
    `prototype_required` TINYINT(1) DEFAULT NULL COMMENT 'Whether prototype is required',
    `needs_continuation` TINYINT(1) DEFAULT NULL COMMENT 'Whether task should continue',
    `pipeline_status` VARCHAR(20) DEFAULT NULL COMMENT 'Latest pipeline status',
    `preview_status` VARCHAR(20) DEFAULT NULL COMMENT 'Preview status',
    `preview_error` TEXT DEFAULT NULL COMMENT 'Preview error',
    `command_history` JSON DEFAULT NULL COMMENT 'Command execution records',
    `pipeline_runs` JSON DEFAULT NULL COMMENT 'Pipeline run records',
    `events` JSON DEFAULT NULL COMMENT 'Runtime events',
    `pending_confirmation` JSON DEFAULT NULL COMMENT 'Pending high-risk confirmation',
    `pending_user_input` JSON DEFAULT NULL COMMENT 'Pending structured user intervention',
    `interventions` JSON DEFAULT NULL COMMENT 'Intervention history',
    `completion_report` JSON DEFAULT NULL COMMENT 'Structured completion report',
    `active_intent_route` JSON DEFAULT NULL COMMENT 'Latest intent route',
    `active_execution_plan` JSON DEFAULT NULL COMMENT 'Latest execution plan',
    `task_capability_profile` JSON DEFAULT NULL COMMENT 'Resolved task capability profile',
    `retrieval_plan` JSON DEFAULT NULL COMMENT 'Workspace retrieval plan',
    `retrieval_guard` JSON DEFAULT NULL COMMENT 'Retrieval guard state',
    `queued_at` VARCHAR(40) DEFAULT NULL COMMENT 'Queue timestamp',
    `lease_owner` VARCHAR(128) DEFAULT NULL COMMENT 'Queue lease owner',
    `lease_until` DATETIME DEFAULT NULL COMMENT 'Queue lease expiry',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (`id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_created_at` (`created_at`),
    INDEX `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AutoCode tasks';
